os:
  - linux

language: d

d:
  - ldc
  # - dmd

env:
  - ARCH="x86_64"

addons:
  apt:
    packages:
      - clinfo
      - opencl-headers
      - libclang-6.0-dev

cache: apt

script:
  - clinfo
  - dub run
